### ISSUE TITLE
Identify API

### ISSUE THREAD

**Issue by fpierreRun** [fpierreRun/BeerMe#5]
Find 2 server Side APIs

**Comment by jleitz27** [comment]
Beer: https://www.openbrewerydb.org/documentation/01-listbreweries 

Google maps/places: https://developers.google.com/maps/documentation/places/web-service

**Comment by jleitz27** [comment]
maps https://www.microsoft.com/en-us/maps

**Comment by jleitz27** [comment]
https://developers.google.com/waze/deeplinks
